### ISSUE TITLE
Error while updating db

### ISSUE THREAD

**Issue by saurabhgupta050890** [codereverser/casparser-isin#11]
Platform: Mac OS Monterey V12.6

Command: `casparser-isin --update`

Error: 
`Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1257, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1303, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1252, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1012, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 952, in send
    self.connect()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1426, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/casparser-isin", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/casparser_isin/cli.py", line 123, in main
    update_isin_db()
  File "/usr/local/lib/python3.9/site-packages/casparser_isin/cli.py", line 92, in update_isin_db
    remote_meta, local_meta = get_isin_db_details()
  File "/usr/local/lib/python3.9/site-packages/casparser_isin/cli.py", line 54, in get_isin_db_details
    with request.urlopen(build_request(META_URL)) as response:
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)>`

**Comment by codereverser** [comment]
I'm unable to reproduce this in the same OS :( 

The SSL certificate error should not happen, as the packages are entirely hosted in the cloud. 
Can you please give it a try again? 

```
❯ casparser-isin --update
2023-01-24 07:57:10,835 - INFO - Fetching remote isin db metadata
2023-01-24 07:57:11,284 - INFO - Local db version  : 2023.1.16
2023-01-24 07:57:11,285 - INFO - Remote db version : 2023.1.24
2023-01-24 07:57:11,285 - INFO - Fetching database version :: 2023.1.24
2023-01-24 07:57:15,309 - INFO - Updated casparser-isin database.

❯ casparser-isin --update
2023-01-24 07:57:20,398 - INFO - Fetching remote isin db metadata
2023-01-24 07:57:20,829 - INFO - Local db version  : 2023.1.24
2023-01-24 07:57:20,829 - INFO - Remote db version : 2023.1.24
2023-01-24 07:57:20,829 - INFO - casparser-isin database is already upto date
```

**Comment by saurabhgupta050890** [comment]
Not sure what is different on my setup. But having this error for this command. I am able to download the latest db via curl though.

Just to further inform my python version is `Python 3.9.6` if that helps.

**Comment by saurabhgupta050890** [comment]
Figured a solution. Since I installed python via homebrew certificates are not installed. 

Need to run the following script:
https://github.com/Unbabel/COMET/issues/29#issuecomment-945601519
